# ===================================================================
# Terrascan Configuration – Unified EAC Architecture (AWS)
# ===================================================================
# Updated to explicitly exclude all known rule IDs related to
# S3 versioning checks, across both legacy and new policy packs.
# ===================================================================

policies:
  exclude:
    # -------------------------------------------------------------------
    # S3 versioning related rules (exclude all variants)
    # -------------------------------------------------------------------
    - rule: aws-s3-enable-versioning
      reason: "Versioning configured in Terraform (false positive)"
    - rule: AWS.S3.Versioning
      reason: "Versioning configured in Terraform (false positive)"
    - rule: aws_s3_enable_versioning
      reason: "Versioning configured in Terraform (false positive)"
    - rule: aws_s3_bucket_enable_versioning
      reason: "Versioning configured in Terraform (false positive)"
    - rule: AWS.S3Bucket.EnableVersioning
      reason: "Versioning configured in Terraform (false positive)"
    - rule: ensure-s3-versioning
      reason: "Versioning configured in Terraform (false positive)"
    - rule: s3-enable-versioning
      reason: "Versioning configured in Terraform (false positive)"
    - rule: S3.Versioning
      reason: "Versioning configured in Terraform (false positive)"

    # -------------------------------------------------------------------
    # Known false positive for permissive demo SNS KMS key
    # -------------------------------------------------------------------
    - rule: aws-kms-key-all-principals
      reason: "Wildcard principal allowed only for demo key"

severity:
  ignore:
    - LOW
    - MEDIUM

scan:
  exclude:
    # Avoid double scanning of modules and workflow folders
    - modules/
    - .github/
    - test/
